export default {
  project: [
    '_id',
    'name',
    'pipeline_count',
    'organization_id',
    'created',
    'modified',
  ],
  organization: [
    '_id',
    'name',
    'contact_name',
    'contact_email',
    'plan_quotas',
    'created',
    'modified',
  ],
  run: [
    '_id',
    'organization_id',
    'job_id',
    'status',
    'created',
    'started',
    'finished',
    'suppress_events',
    'suppress_outputs',
    'suppress_vars',
  ],
  runEvent: [
    '_id',
    'operation_id',
    'occurred',
    'code',
    'message',
    'details',
    'level',
    'output',
  ],
  job: [
    '_id',
    'project_id',
    'pipeline_id',
    'pipeline_revision_id',
    'pipeline_version_id',
    'created',
    'name',
    'number',
    'enabled',
    'trigger_type',
    'schedule',
    'suppress_outputs',
    'suppress_vars',
    'suppress_events',
    'disable_on_failure',
    'variables',
  ],
};
